### ISSUE TITLE
Heap size for Myria Deployment

### ISSUE THREAD

**Issue by jortiz16** [uwescience/myria-ec2#16]
I've been trying to increase the memory for clusters I've launched on EC2. I realized that the JVM memory usage for the workers hasn't been changing when I change the HEAP parameter in my myriacluster.config file. 

This is because in myriaplugin.py, it is updating the heap for myria deployment as:

```heap='heap = ' + self.heap if self.heap else ''```

The problem is that the Myria only reads the heap parameter from the deployment as ```max_heap_size```, not ```heap```. Changing the line to the following has worked for me:

```heap='max_heap_size = ' + self.heap if self.heap else ''```

**Comment by BrandonHaynes** [comment]
Yikes, thanks for pointing this out.  Another reason I need to pull the deployment-creation logic from here and use the new create_deployment.py script.

Fixed by 4ead4181cef134fba46caebb777ce229e78a2b46.
